// Gallery items — exact labels from website-content.txt
export const galleryItems = [
  { id: 1, label: 'MSS-MF SELF LUBE', category: 'Bearings' },
  { id: 2, label: 'MSS-MP PRE LUBE', category: 'Bearings' },
  { id: 3, label: 'MSS-BIM BI-METAL', category: 'Bearings' },
  { id: 4, label: 'MSS-MB SOLID BUSH', category: 'Bearings' },
  { id: 5, label: 'MSS-MITHLON', category: 'Bearings' },
  { id: 6, label: 'SPRING ENERGIZED LIP SEAL', category: 'Seals' },
  { id: 7, label: 'STEM PACKING', category: 'Seals' },
  { id: 8, label: 'PEEK SEAT RING', category: 'Seals' },
  { id: 9, label: 'SEAT SEAL', category: 'Seals' },
  { id: 10, label: 'PTFE CHEVRON PACKING', category: 'Seals' },
  { id: 11, label: 'GLAND PACKING', category: 'Seals' },
  { id: 12, label: 'O-RING', category: 'Seals' },
  { id: 13, label: 'PTFE CARBON GRAPHITE CHEVRON PACKING', category: 'Seals' },
  { id: 14, label: 'PTFE CARBON GRAPHITE SEAT', category: 'Seals' },
  { id: 15, label: 'PTFE CAVITY SEAT', category: 'Seals' },
  { id: 16, label: 'PTFE SEAT', category: 'Seals' },
  { id: 17, label: 'PTFE SLEEVE', category: 'Seals' },
  { id: 18, label: 'PTFE PLUG', category: 'Seals' },
  { id: 19, label: 'PTFE LINED', category: 'Seals' },
  { id: 20, label: 'DEVLON SEAT RING', category: 'Seals' },
  { id: 21, label: 'DEVLON INSERT METAL SEAT', category: 'Seals' },
  { id: 22, label: 'PISTON SEALS', category: 'Hydraulic' },
  { id: 23, label: 'ROD SEALS', category: 'Hydraulic' },
  { id: 24, label: 'WEAR RINGS', category: 'Hydraulic' },
  { id: 25, label: 'WIPER SEALS', category: 'Hydraulic' },
  { id: 26, label: 'DIAPHRAGM', category: 'AODD' },
  { id: 27, label: 'PTFE BALL', category: 'AODD' },
  { id: 28, label: 'PTFE O-RING', category: 'AODD' },
  { id: 29, label: 'PEEK - THRUST WASHER', category: 'Transmission' },
  { id: 30, label: 'PTFE - TRANSMISSION SEAL', category: 'Transmission' },
  { id: 31, label: 'PEEK - SPLIT LOCK WASHER', category: 'Transmission' },
  { id: 32, label: 'BI-METAL PTFE BUSHINGS', category: 'Bearings' },
  { id: 33, label: 'STUFFING BOX BEARING', category: 'Bearings' },
  { id: 34, label: 'LINE SHAFT BEARING', category: 'Bearings' },
  { id: 35, label: 'PTFE NOZZLES', category: 'Power Grid' },
  { id: 36, label: 'ENCAPSULATED O-RING', category: 'Seals' },
  { id: 37, label: 'MITH PLATE', category: 'Compressors', image: '/src/pages/Products/MITH-PLATE/assets/mith-plate.png' },
];

export const galleryCategories = ['All', 'Seals', 'Bearings', 'Hydraulic', 'AODD', 'Transmission', 'Power Grid', 'Compressors'];
